name: "git-publish-generated-branch"
description: "create & update derived git branches for hosting generated content"

inputs:
  ARGS:
    description: "args to pass to the git-publish-generated-branch CLI"
    required: true
    default: ""

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        repository: kiprasmel/git-publish-generated-branch
        ref: v0
        path: git-publish-generated-branch

    - run: ./git-publish-generated-branch/git-publish-generated-branch ${{ inputs.ARGS }}
      shell: bash
