name: "git-publish-generated-branch"
description: "create & update derived git branches for hosting generated content"

inputs:
  ARGS:
    description: "args to pass to the git-publish-generated-branch CLI"
    required: true
    default: ""

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.ARGS }}
